language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install coverage pytest

script:
  - coverage run -m pytest
  - black --check
  - isort --check-only

after_success:
  - bash <(curl -s https://codecov.io/bash)
